[render]
width = 1920
height = 1080
font = "/usr/share/fonts/liberation/LiberationMono-Regular.ttf"
font_size = 38 
text_color = "#ffffff"
background_color = "#000000"
text_align = "centre"
char_align = "left"
# bg_img = "/path/to/img.png"
opacity = 1.0 

[wallpaper]
path="~/.config/textwal2/output.png"
set_command="~/.config/textwal2/set-wallpaper.sh"
